title: Github Page with jekyll
author: BlazzzingSheep
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  This descriptionb is for google search test usage f github page with jekyll.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

